workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - release
      node: 18.16.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Create assets directory
        script: |
          mkdir -p android/app/src/main/assets
      - name: Bundle React Native JS
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
      - name: Build Android release
        script: |
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
